version: 2

sources:
  - name: postgres_public
    database: postgres
    schema: public
    tables:
      - name: activity

  - name: pipedrive
    database: postgres
    schema: public
    tables:
      - name: activity  
      - name: deal_changes
      - name: stages  
      - name: activity_types
      - name: users
